### ISSUE TITLE
_NET_WORKAREA property not found

### ISSUE THREAD

**Issue by DavidBJaffe** [phR0ze/wmctl#1]
This crate is very cool!  I tried copying the Window Manager Info `fn main()` and got the error
`WmCtl(PropertyNotFound("_NET_WORKAREA"))`.  This comes from the line
```
let wmctl = WmCtl::connect().unwrap();
```
I am able to run the Linux standard command `wmctrl -l`.

**Comment by phR0ze** [comment]
@DavidBJaffe which Linux Distro and Window Manager are you using?

**Comment by DavidBJaffe** [comment]
This is Ubuntu 22.04.  It is running through Docker on a Mac, which is an admittedly weird use case.  How can I determine which window manager is in use?

**Comment by DavidBJaffe** [comment]
I have a GUI app, and my actual goal was to put a button on the app to screen capture it.  That started by finding the window id.  However, it appears this won't work at all under Wayland, so I think I will abandon the project.

**Comment by psychon** [comment]
Some random idea: `xprop -root`. This should print all properties of the root window. On one hand this should show us what is up with `_NET_WORKAREA`. On the other hand, this might provide information about the window manager:
```
$ xprop -root | grep '"i3"'
_NET_WM_NAME(UTF8_STRING) = "i3"
```

**Comment by psychon** [comment]
Oh, hey, `i3` actually reproduces the problem!
```
$ xprop -root _NET_WORKAREA
_NET_WORKAREA:  not found.
$ xtrace cargo run info
[...]
000:<:0056: 24: Request(20): GetProperty delete=false(0x00) window=0x00000769 property=0x1ac("_NET_WORKAREA") type=0x6("CARDINAL") long-offset=0x00000000 long-length=0xffffffff
000:>:0056:32: Reply to GetProperty: type=None(0x0) bytes-after=0x00000000 
 error: witcher::Error: property _NET_WORKAREA was not found
symbol: wmctl::init
    at: src/main.rs:214:9
symbol: wmctl::main
    at: src/main.rs:255:11
symbol: __libc_start_call_main
    at: ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
```

**Comment by gregovilardo** [comment]
I'm trying to obtain the workspaces for i3, and it seems that they won't implement _NET_WORKAREA (as mentioned here: https://github.com/qtile/qtile/issues/847#issuecomment-172625433). Does this mean there's no way to execute WmCtl::connect() without having that variable set?

**Comment by phR0ze** [comment]
tiling window managers like ***i3*** or ***qtile*** don't typically work well with the manual shape and placement features offered by ***wmctl*** as they control the placement of the windows very carefully for tiling. that said I went ahead and removed the dependency on **_NET_WORKAREA** and it will just fall back on the screen total size. This should allow for greater compatibility with window manager's that have only partial [EWMH](https://specifications.freedesktop.org/wm-spec/latest) support. You can find the unreleased change in the main branch
